package com.rarysoft.u4.model.graphics;

import java.util.stream.Stream;

public enum Tile {
    DEEP_WATER(0, 0, true, false, false, false),
    MEDIUM_WATER(1, 0, true, false, false, false),
    SHALLOW_WATER(2, 0, true, false, false, false),
    SWAMP(3, 90, false, true, false, false),
    GRASSLANDS(4, 100, true, false, false, false),
    SCRUBLAND(5, 60, true, false, false, false),
    FOREST(6, 78, true, false, true, false),
    HILLS(7, 50, true, false, false, false),
    MOUNTAINS(8, 0, true, false, true, false),
    DUNGEON_ENTRANCE(9, 100, true, true, false, false),
    TOWN(10, 100, true, true, false, false),
    CASTLE(11, 100, true, true, false, false),
    VILLAGE(12, 100, true, true, false , false),
    CASTLE_BRITANNIA_WEST(13, 0, false, false, false, false),
    CASTLE_BRITANNIA_ENTRANCE(14, 100, true, true, false, false),
    CASTLE_BRITANNIA_EAST(15, 0, false, false, false, false),
    SHIP_WEST(16, 100, true, false, false, false),
    SHIP_NORTH(17, 100, true, false, false, false),
    SHIP_EAST(18, 100, true, false, false, false),
    SHIP_SOUTH(19, 100, true, false, false, false),
    HORSE_WEST(20, 100, true, false, false, false),
    HORSE_EAST(21, 100, true, false, false, false),
    TILE_FLOOR(22, 100, true, false, false, false),
    BRIDGE(23, 100, true, false, false, false),
    BALLOON(24, 100, true, false, false, false),
    BRIDGE_NORTH(25, 100, true, false, false, false),
    BRIDGE_SOUTH(26, 100, true, false, false, false),
    LADDER_UP(27, 100, true, true, false, false),
    LADDER_DOWN(28, 100, true, true, false, false),
    RUINS(29, 100, true, true, false, false),
    SHRINE(30, 100, true, true, false, false),
    AVATAR(31, 0, false, false, false, false),
    MAGE_1(32, 0, false, false, false, false),
    MAGE_2(33, 0, false, false, false, false),
    BARD_1(34, 0, false, false, false, false),
    BARD_2(35, 0, false, false, false, false),
    FIGHTER_1(36, 0, false, false, false, false),
    FIGHTER_2(37, 0, false, false, false, false),
    DRUID_1(38, 0, false, false, false, false),
    DRUID_2(39, 0, false, false, false, false),
    TINKER_1(40, 0, false, false, false, false),
    TINKER_2(41, 0, false, false, false, false),
    PALADIN_1(42, 0, false, false, false, false),
    PALADIN_2(43, 0, false, false, false, false),
    RANGER_1(44, 0, false, false, false, false),
    RANGER_2(45, 0, false, false, false, false),
    SHEPHERD_1(46, 0, false, false, false, false),
    SHEPHERD_2(47, 0, false, false, false, false),
    COLUMN(48, 0, false, false, false, false),
    WHITE_SW(49, 0, false, false, false, false),
    WHITE_SE(50, 0, false, false, false, false),
    WHITE_NW(51, 0, false, false, false, false),
    WHITE_NE(52, 0, false, false, false, false),
    MAST(53, 0, false, false, false, false),
    SHIPS_WHEEL(54, 0, false, false, false, false),
    ROCKS(55, 0, false, false, false, false),
    LYIN_DOWN(56, 0, false, false, false, false),
    STONE_WALL(57, 0, false, false, true, false),
    LOCKED_DOOR(58, 0, false, false, false, false),
    UNLOCKED_DOOR(59, 0, false, false, false, false),
    CHEST(60, 100, false, false, false, false),
    ANKH(61, 0, false, false, false, false),
    BRICK_FLOOR(62, 100, true, false, false, false),
    WOODEN_PLANKS(63, 100, true, false, false, false),
    MOONGATE_1(64, 0, false, false, false, false),
    MOONGATE_2(65, 0, false, false, false, false),
    MOONGATE_3(66, 0, false, false, false, false),
    MOONGATE_4(67, 100, false, true, false, false),
    POISON_FIELD(68, 100, true, false, false, false),
    ENERGY_FIELD(69, 100, true, false, false, false),
    FIRE_FIELD(70, 100, true, false, false, false),
    SLEEP_FIELD(71, 100, true, false, false, false),
    SOLID_BARRIER(72, 0, false, false, false, false),
    HIDDEN_PASSAGE(73, 100, false, false, true, false),
    ALTAR(74, 0, false, false, false, false),
    SPIT(75, 0, false, false, false, false),
    LAVA_FLOW(76, 0, false, false, false, false),
    MISSILE(77, 0, false, false, false, false),
    MAGIC_SPHERE(78, 0, false, false, false, false),
    ATTACK_FLASH(79, 0, false, false, false, false),
    GUARD_1(80, 0, false, false, false, false),
    GUARD_2(81, 0, false, false, false, false),
    CITIZEN_1(82, 0, false, false, false, false),
    CITIZEN_2(83, 0, false, false, false, false),
    SINGING_BARD_1(84, 0, false, false, false, false),
    SINGING_BARD_2(85, 0, false, false, false, false),
    JESTER_1(86, 0, false, false, false, false),
    JESTER_2(87, 0, false, false, false, false),
    BEGGAR_1(88, 0, false, false, false, false),
    BEGGAR_2(89, 0, false, false, false, false),
    CHILD_2(91, 0, false, false, false, false),
    CHILD_1(90, 0, false, false, false, false),
    BULL_1(92, 0, false, false, false, false),
    BULL_2(93, 0, false, false, false, false),
    LORD_BRITISH_1(94, 0, false, false, false, false),
    LORD_BRITISH_2(95, 0, false, false, false, false),
    A(96, 0, false, false, false, true),
    B(97, 0, false, false, false, true),
    C(98, 0, false, false, false, true),
    D(99, 0, false, false, false, true),
    E(100, 0, false, false, false, true),
    F(101, 0, false, false, false, true),
    G(102, 0, false, false, false, true),
    H(103, 0, false, false, false, true),
    I(104, 0, false, false, false, true),
    J(105, 0, false, false, false, true),
    K(106, 0, false, false, false, true),
    L(107, 0, false, false, false, true),
    M(108, 0, false, false, false, true),
    N(109, 0, false, false, false, true),
    O(110, 0, false, false, false, true),
    P(111, 0, false, false, false, true),
    Q(112, 0, false, false, false, true),
    R(113, 0, false, false, false, true),
    S(114, 0, false, false, false, true),
    T(115, 0, false, false, false, true),
    U(116, 0, false, false, false, true),
    V(117, 0, false, false, false, true),
    W(118, 0, false, false, false, true),
    X(119, 0, false, false, false, true),
    Y(120, 0, false, false, false, true),
    Z(121, 0, false, false, false, true),
    SPACE(122, 0, false, false, false, true),
    RIGHT(123, 0, false, false, false, false),
    LEFT(124, 0, false, false, false, false),
    WINDOW(125, 0, false, false, false, false),
    BLANK(126, 0, false, false, false, false),
    BRICK_WALL(127, 0, false, false, true, false),
    PIRATE_SHIP_WEST(128, 0, false, false, false, false),
    PIRATE_SHIP_NORTH(129, 0, false, false, false, false),
    PIRATE_SHIP_EAST(130, 0, false, false, false, false),
    PIRATE_SHIP_SOUTH(131, 0, false, false, false, false),
    NIXIE_1(132, 0, false, false, false, false),
    NIXIE_2(133, 0, false, false, false, false),
    GIANT_SQUID_1(134, 0, false, false, false, false),
    GIANT_SQUID_2(135, 0, false, false, false, false),
    SEA_SERPENT_1(136, 0, false, false, false, false),
    SEA_SERPENT_2(137, 0, false, false, false, false),
    SEAHORSE_1(138, 0, false, false, false, false),
    SEAHORSE_2(139, 0, false, false, false, false),
    WHIRLPOOL_1(140, 0, false, false, false, false),
    WHIRLPOOL_2(141, 0, false, false, false, false),
    STORM_1(142, 0, false, false, false, false),
    STORM_2(143, 0, false, false, false, false),
    RAT_1(144, 0, false, false, false, false),
    RAT_2(145, 0, false, false, false, false),
    RAT_3(146, 0, false, false, false, false),
    RAT_4(147, 0, false, false, false, false),
    BAT_1(148, 0, false, false, false, false),
    BAT_2(149, 0, false, false, false, false),
    BAT_3(150, 0, false, false, false, false),
    BAT_4(151, 0, false, false, false, false),
    GIANT_SPIDER_1(152, 0, false, false, false, false),
    GIANT_SPIDER_2(153, 0, false, false, false, false),
    GIANT_SPIDER_3(154, 0, false, false, false, false),
    GIANT_SPIDER_4(155, 0, false, false, false, false),
    GHOST_1(156, 0, false, false, false, false),
    GHOST_2(157, 0, false, false, false, false),
    GHOST_3(158, 0, false, false, false, false),
    GHOST_4(159, 0, false, false, false, false),
    SLIME_1(160, 0, false, false, false, false),
    SLIME_2(161, 0, false, false, false, false),
    SLIME_3(162, 0, false, false, false, false),
    SLIME_4(163, 0, false, false, false, false),
    TROLL_1(164, 0, false, false, false, false),
    TROLL_2(165, 0, false, false, false, false),
    TROLL_3(166, 0, false, false, false, false),
    TROLL_4(167, 0, false, false, false, false),
    GREMLIN_1(168, 0, false, false, false, false),
    GREMLIN_2(169, 0, false, false, false, false),
    GREMLIN_3(170, 0, false, false, false, false),
    GREMLIN_4(171, 0, false, false, false, false),
    MIMIC_1(172, 0, false, false, false, false),
    MIMIC_2(173, 0, false, false, false, false),
    MIMIC_3(174, 0, false, false, false, false),
    MIMIC_4(175, 0, false, false, false, false),
    REAPER_1(176, 0, false, false, false, false),
    REAPER_2(177, 0, false, false, false, false),
    REAPER_3(178, 0, false, false, false, false),
    REAPER_4(179, 0, false, false, false, false),
    INSECT_SWARM_1(180, 0, false, false, false, false),
    INSECT_SWARM_2(181, 0, false, false, false, false),
    INSECT_SWARM_3(182, 0, false, false, false, false),
    INSECT_SWARM_4(183, 0, false, false, false, false),
    GAZER_1(184, 0, false, false, false, false),
    GAZER_2(185, 0, false, false, false, false),
    GAZER_3(186, 0, false, false, false, false),
    GAZER_4(187, 0, false, false, false, false),
    PHANTOM_1(188, 0, false, false, false, false),
    PHANTOM_2(189, 0, false, false, false, false),
    PHANTOM_3(190, 0, false, false, false, false),
    PHANTOM_4(191, 0, false, false, false, false),
    ORC_1(192, 0, false, false, false, false),
    ORC_2(193, 0, false, false, false, false),
    ORC_3(194, 0, false, false, false, false),
    ORC_4(195, 0, false, false, false, false),
    SKELETON_1(196, 0, false, false, false, false),
    SKELETON_2(197, 0, false, false, false, false),
    SKELETON_3(198, 0, false, false, false, false),
    SKELETON_4(199, 0, false, false, false, false),
    ROGUE_1(200, 0, false, false, false, false),
    ROGUE_2(201, 0, false, false, false, false),
    ROGUE_3(202, 0, false, false, false, false),
    ROGUE_4(203, 0, false, false, false, false),
    PYTHON_1(204, 0, false, false, false, false),
    PYTHON_2(205, 0, false, false, false, false),
    PYTHON_3(206, 0, false, false, false, false),
    PYTHON_4(207, 0, false, false, false, false),
    ETTIN_1(208, 0, false, false, false, false),
    ETTIN_2(209, 0, false, false, false, false),
    ETTIN_3(210, 0, false, false, false, false),
    ETTIN_4(211, 0, false, false, false, false),
    HEADLESS_1(212, 0, false, false, false, false),
    HEADLESS_2(213, 0, false, false, false, false),
    HEADLESS_3(214, 0, false, false, false, false),
    HEADLESS_4(215, 0, false, false, false, false),
    CYCLOPS_1(216, 0, false, false, false, false),
    CYCLOPS_2(217, 0, false, false, false, false),
    CYCLOPS_3(218, 0, false, false, false, false),
    CYCLOPS_4(219, 0, false, false, false, false),
    WISP_1(220, 0, false, false, false, false),
    WISP_2(221, 0, false, false, false, false),
    WISP_3(222, 0, false, false, false, false),
    WISP_4(223, 0, false, false, false, false),
    EVIL_MAGE_1(224, 0, false, false, false, false),
    EVIL_MAGE_2(225, 0, false, false, false, false),
    EVIL_MAGE_3(226, 0, false, false, false, false),
    EVIL_MAGE_4(227, 0, false, false, false, false),
    LICH_1(228, 0, false, false, false, false),
    LICH_2(229, 0, false, false, false, false),
    LICH_3(230, 0, false, false, false, false),
    LICH_4(231, 0, false, false, false, false),
    LAVA_LIZARD_1(232, 0, false, false, false, false),
    LAVA_LIZARD_2(233, 0, false, false, false, false),
    LAVA_LIZARD_3(234, 0, false, false, false, false),
    LAVA_LIZARD_4(235, 0, false, false, false, false),
    ZORN_1(236, 0, false, false, false, false),
    ZORN_2(237, 0, false, false, false, false),
    ZORN_3(238, 0, false, false, false, false),
    ZORN_4(239, 0, false, false, false, false),
    DAEMON_1(240, 0, false, false, false, false),
    DAEMON_2(241, 0, false, false, false, false),
    DAEMON_3(242, 0, false, false, false, false),
    DAEMON_4(243, 0, false, false, false, false),
    HYDRA_1(244, 0, false, false, false, false),
    HYDRA_2(245, 0, false, false, false, false),
    HYDRA_3(246, 0, false, false, false, false),
    HYDRA_4(247, 0, false, false, false, false),
    DRAGON_1(248, 0, false, false, false, false),
    DRAGON_2(249, 0, false, false, false, false),
    DRAGON_3(250, 0, false, false, false, false),
    DRAGON_4(251, 0, false, false, false, false),
    BALRON_1(252, 0, false, false, false, false),
    BALRON_2(253, 0, false, false, false, false),
    BALRON_3(254, 0, false, false, false, false),
    BALRON_4(255, 0, false, false, false, false);

    private final int index;

    private final int walkability;

    private final boolean isGroundTile;

    private final boolean isPortal;

    private final boolean isOpaque;

    private final boolean canTalkThrough;
    
    Tile(int index, int walkability, boolean isGroundTile, boolean isPortal, boolean isOpaque, boolean canTalkThrough) {
        this.index = index;
        this.isGroundTile = isGroundTile;
        this.isPortal = isPortal;
        this.walkability = walkability;
        this.isOpaque = isOpaque;
        this.canTalkThrough = canTalkThrough;
    }

    public static Tile forIndex(int index) {
        return Stream.of(values()).filter(tile -> tile.index() == index).findAny().orElseThrow(IllegalArgumentException::new);
    }

    public int index() {
        return index;
    }

    public int walkability() {
        return walkability;
    }

    public boolean isGroundTile() {
        return isGroundTile;
    }

    public boolean isPortal() {
        return isPortal;
    }

    public boolean isOpaque() {
        return isOpaque;
    }

    public boolean canTalkThrough() {
        return canTalkThrough;
    }
}
