package com.rarysoft.u4.model.graphics;

import java.util.stream.Stream;

import static com.rarysoft.u4.model.graphics.TileType.*;

public enum Tile {
    DEEP_WATER(0, GROUND, 0, false, false),
    MEDIUM_WATER(1, GROUND, 0, false, false),
    SHALLOW_WATER(2, GROUND, 0, false, false),
    SWAMP(3, GROUND, 90, false, false),
    GRASSLANDS(4, GROUND, 100, false, false),
    SCRUBLAND(5, GROUND, 60, false, false),
    FOREST(6, GROUND, 78, true, false),
    HILLS(7, GROUND, 50, false, false),
    MOUNTAINS(8, GROUND, 0, true, false),
    DUNGEON_ENTRANCE(9, PORTAL, 100, false, false),
    TOWN(10, PORTAL, 100, false, false),
    CASTLE(11, PORTAL, 100, false, false),
    VILLAGE(12, PORTAL, 100, false , false),
    CASTLE_BRITANNIA_WEST(13, GROUND, 0, false, false),
    CASTLE_BRITANNIA_ENTRANCE(14, PORTAL, 100, false, false),
    CASTLE_BRITANNIA_EAST(15, GROUND, 0, false, false),
    SHIP_WEST(16, TRANSPORT, 100, false, false),
    SHIP_NORTH(17, TRANSPORT, 100, false, false),
    SHIP_EAST(18, TRANSPORT, 100, false, false),
    SHIP_SOUTH(19, TRANSPORT, 100, false, false),
    HORSE_WEST(20, TRANSPORT, 100, false, false),
    HORSE_EAST(21, TRANSPORT, 100, false, false),
    TILE_FLOOR(22, GROUND, 100, false, false),
    BRIDGE(23, GROUND, 100, false, false),
    BALLOON(24, TRANSPORT, 100, false, false),
    BRIDGE_NORTH(25, GROUND, 100, false, false),
    BRIDGE_SOUTH(26, GROUND, 100, false, false),
    LADDER_UP(27, PORTAL, 100, false, false),
    LADDER_DOWN(28, PORTAL, 100, false, false),
    RUINS(29, PORTAL, 100, false, false),
    SHRINE(30, PORTAL, 100, false, false),
    AVATAR(31, PLAYER, 0, false, false),
    MAGE_1(32, NPC, 0, false, false),
    MAGE_2(33, NPC, 0, false, false),
    BARD_1(34, NPC, 0, false, false),
    BARD_2(35, NPC, 0, false, false),
    FIGHTER_1(36, NPC, 0, false, false),
    FIGHTER_2(37, NPC, 0, false, false),
    DRUID_1(38, NPC, 0, false, false),
    DRUID_2(39, NPC, 0, false, false),
    TINKER_1(40, NPC, 0, false, false),
    TINKER_2(41, NPC, 0, false, false),
    PALADIN_1(42, NPC, 0, false, false),
    PALADIN_2(43, NPC, 0, false, false),
    RANGER_1(44, NPC, 0, false, false),
    RANGER_2(45, NPC, 0, false, false),
    SHEPHERD_1(46, NPC, 0, false, false),
    SHEPHERD_2(47, NPC, 0, false, false),
    COLUMN(48, OBSTACLE, 0, false, false),
    WHITE_SW(49, OBSTACLE, 0, false, false),
    WHITE_SE(50, OBSTACLE, 0, false, false),
    WHITE_NW(51, OBSTACLE, 0, false, false),
    WHITE_NE(52, OBSTACLE, 0, false, false),
    MAST(53, OBSTACLE, 0, false, false),
    SHIPS_WHEEL(54, OBSTACLE, 0, false, false),
    ROCKS(55, OBSTACLE, 0, false, false),
    LYIN_DOWN(56, OBSTACLE, 0, false, false),
    STONE_WALL(57, OBSTACLE, 0, true, false),
    LOCKED_DOOR(58, OBSTACLE, 0, true, false),
    UNLOCKED_DOOR(59, OBSTACLE, 0, true, false),
    CHEST(60, SPECIAL, 100, false, false),
    ANKH(61, OBSTACLE, 0, false, false),
    BRICK_FLOOR(62, GROUND, 100, false, false),
    WOODEN_PLANKS(63, GROUND, 100, false, false),
    MOONGATE_1(64, OBSTACLE, 0, false, false),
    MOONGATE_2(65, OBSTACLE, 0, false, false),
    MOONGATE_3(66, OBSTACLE, 0, false, false),
    MOONGATE_4(67, PORTAL, 100, false, false),
    POISON_FIELD(68, GROUND, 100, false, false),
    ENERGY_FIELD(69, GROUND, 100, false, false),
    FIRE_FIELD(70, GROUND, 100, false, false),
    SLEEP_FIELD(71, GROUND, 100, false, false),
    SOLID_BARRIER(72, OBSTACLE, 0, false, false),
    HIDDEN_PASSAGE(73, GROUND, 100, true, false),
    ALTAR(74, OBSTACLE, 0, false, false),
    SPIT(75, OBSTACLE, 0, false, false),
    LAVA_FLOW(76, OBSTACLE, 0, false, false),
    MISSILE(77, SPECIAL, 0, false, false),
    MAGIC_SPHERE(78, SPECIAL, 0, false, false),
    ATTACK_FLASH(79, SPECIAL, 0, false, false),
    GUARD_1(80, NPC, 0, false, false),
    GUARD_2(81, NPC, 0, false, false),
    CITIZEN_1(82, NPC, 0, false, false),
    CITIZEN_2(83, NPC, 0, false, false),
    SINGING_BARD_1(84, NPC, 0, false, false),
    SINGING_BARD_2(85, NPC, 0, false, false),
    JESTER_1(86, NPC, 0, false, false),
    JESTER_2(87, NPC, 0, false, false),
    BEGGAR_1(88, NPC, 0, false, false),
    BEGGAR_2(89, NPC, 0, false, false),
    CHILD_1(90, NPC, 0, false, false),
    CHILD_2(91, NPC, 0, false, false),
    BULL_1(92, NPC, 0, false, false),
    BULL_2(93, NPC, 0, false, false),
    LORD_BRITISH_1(94, NPC, 0, false, false),
    LORD_BRITISH_2(95, NPC, 0, false, false),
    A(96, OBSTACLE, 0, false, true),
    B(97, OBSTACLE, 0, false, true),
    C(98, OBSTACLE, 0, false, true),
    D(99, OBSTACLE, 0, false, true),
    E(100, OBSTACLE, 0, false, true),
    F(101, OBSTACLE, 0, false, true),
    G(102, OBSTACLE, 0, false, true),
    H(103, OBSTACLE, 0, false, true),
    I(104, OBSTACLE, 0, false, true),
    J(105, OBSTACLE, 0, false, true),
    K(106, OBSTACLE, 0, false, true),
    L(107, OBSTACLE, 0, false, true),
    M(108, OBSTACLE, 0, false, true),
    N(109, OBSTACLE, 0, false, true),
    O(110, OBSTACLE, 0, false, true),
    P(111, OBSTACLE, 0, false, true),
    Q(112, OBSTACLE, 0, false, true),
    R(113, OBSTACLE, 0, false, true),
    S(114, OBSTACLE, 0, false, true),
    T(115, OBSTACLE, 0, false, true),
    U(116, OBSTACLE, 0, false, true),
    V(117, OBSTACLE, 0, false, true),
    W(118, OBSTACLE, 0, false, true),
    X(119, OBSTACLE, 0, false, true),
    Y(120, OBSTACLE, 0, false, true),
    Z(121, OBSTACLE, 0, false, true),
    SPACE(122, OBSTACLE, 0, false, true),
    RIGHT(123, OBSTACLE, 0, false, false),
    LEFT(124, OBSTACLE, 0, false, false),
    WINDOW(125, OBSTACLE, 0, false, false),
    BLANK(126, OBSTACLE, 0, false, false),
    BRICK_WALL(127, OBSTACLE, 0, true, false),
    PIRATE_SHIP_WEST(128, MONSTER, 0, false, false),
    PIRATE_SHIP_NORTH(129, MONSTER, 0, false, false),
    PIRATE_SHIP_EAST(130, MONSTER, 0, false, false),
    PIRATE_SHIP_SOUTH(131, MONSTER, 0, false, false),
    NIXIE_1(132, MONSTER, 0, false, false),
    NIXIE_2(133, MONSTER, 0, false, false),
    GIANT_SQUID_1(134, MONSTER, 0, false, false),
    GIANT_SQUID_2(135, MONSTER, 0, false, false),
    SEA_SERPENT_1(136, MONSTER, 0, false, false),
    SEA_SERPENT_2(137, MONSTER, 0, false, false),
    SEAHORSE_1(138, MONSTER, 0, false, false),
    SEAHORSE_2(139, MONSTER, 0, false, false),
    WHIRLPOOL_1(140, MONSTER, 0, false, false),
    WHIRLPOOL_2(141, MONSTER, 0, false, false),
    STORM_1(142, MONSTER, 0, false, false),
    STORM_2(143, MONSTER, 0, false, false),
    RAT_1(144, MONSTER, 0, false, false),
    RAT_2(145, MONSTER, 0, false, false),
    RAT_3(146, MONSTER, 0, false, false),
    RAT_4(147, MONSTER, 0, false, false),
    BAT_1(148, MONSTER, 0, false, false),
    BAT_2(149, MONSTER, 0, false, false),
    BAT_3(150, MONSTER, 0, false, false),
    BAT_4(151, MONSTER, 0, false, false),
    GIANT_SPIDER_1(152, MONSTER, 0, false, false),
    GIANT_SPIDER_2(153, MONSTER, 0, false, false),
    GIANT_SPIDER_3(154, MONSTER, 0, false, false),
    GIANT_SPIDER_4(155, MONSTER, 0, false, false),
    GHOST_1(156, MONSTER, 0, false, false),
    GHOST_2(157, MONSTER, 0, false, false),
    GHOST_3(158, MONSTER, 0, false, false),
    GHOST_4(159, MONSTER, 0, false, false),
    SLIME_1(160, MONSTER, 0, false, false),
    SLIME_2(161, MONSTER, 0, false, false),
    SLIME_3(162, MONSTER, 0, false, false),
    SLIME_4(163, MONSTER, 0, false, false),
    TROLL_1(164, MONSTER, 0, false, false),
    TROLL_2(165, MONSTER, 0, false, false),
    TROLL_3(166, MONSTER, 0, false, false),
    TROLL_4(167, MONSTER, 0, false, false),
    GREMLIN_1(168, MONSTER, 0, false, false),
    GREMLIN_2(169, MONSTER, 0, false, false),
    GREMLIN_3(170, MONSTER, 0, false, false),
    GREMLIN_4(171, MONSTER, 0, false, false),
    MIMIC_1(172, MONSTER, 0, false, false),
    MIMIC_2(173, MONSTER, 0, false, false),
    MIMIC_3(174, MONSTER, 0, false, false),
    MIMIC_4(175, MONSTER, 0, false, false),
    REAPER_1(176, MONSTER, 0, false, false),
    REAPER_2(177, MONSTER, 0, false, false),
    REAPER_3(178, MONSTER, 0, false, false),
    REAPER_4(179, MONSTER, 0, false, false),
    INSECT_SWARM_1(180, MONSTER, 0, false, false),
    INSECT_SWARM_2(181, MONSTER, 0, false, false),
    INSECT_SWARM_3(182, MONSTER, 0, false, false),
    INSECT_SWARM_4(183, MONSTER, 0, false, false),
    GAZER_1(184, MONSTER, 0, false, false),
    GAZER_2(185, MONSTER, 0, false, false),
    GAZER_3(186, MONSTER, 0, false, false),
    GAZER_4(187, MONSTER, 0, false, false),
    PHANTOM_1(188, MONSTER, 0, false, false),
    PHANTOM_2(189, MONSTER, 0, false, false),
    PHANTOM_3(190, MONSTER, 0, false, false),
    PHANTOM_4(191, MONSTER, 0, false, false),
    ORC_1(192, MONSTER, 0, false, false),
    ORC_2(193, MONSTER, 0, false, false),
    ORC_3(194, MONSTER, 0, false, false),
    ORC_4(195, MONSTER, 0, false, false),
    SKELETON_1(196, MONSTER, 0, false, false),
    SKELETON_2(197, MONSTER, 0, false, false),
    SKELETON_3(198, MONSTER, 0, false, false),
    SKELETON_4(199, MONSTER, 0, false, false),
    ROGUE_1(200, MONSTER, 0, false, false),
    ROGUE_2(201, MONSTER, 0, false, false),
    ROGUE_3(202, MONSTER, 0, false, false),
    ROGUE_4(203, MONSTER, 0, false, false),
    PYTHON_1(204, MONSTER, 0, false, false),
    PYTHON_2(205, MONSTER, 0, false, false),
    PYTHON_3(206, MONSTER, 0, false, false),
    PYTHON_4(207, MONSTER, 0, false, false),
    ETTIN_1(208, MONSTER, 0, false, false),
    ETTIN_2(209, MONSTER, 0, false, false),
    ETTIN_3(210, MONSTER, 0, false, false),
    ETTIN_4(211, MONSTER, 0, false, false),
    HEADLESS_1(212, MONSTER, 0, false, false),
    HEADLESS_2(213, MONSTER, 0, false, false),
    HEADLESS_3(214, MONSTER, 0, false, false),
    HEADLESS_4(215, MONSTER, 0, false, false),
    CYCLOPS_1(216, MONSTER, 0, false, false),
    CYCLOPS_2(217, MONSTER, 0, false, false),
    CYCLOPS_3(218, MONSTER, 0, false, false),
    CYCLOPS_4(219, MONSTER, 0, false, false),
    WISP_1(220, MONSTER, 0, false, false),
    WISP_2(221, MONSTER, 0, false, false),
    WISP_3(222, MONSTER, 0, false, false),
    WISP_4(223, MONSTER, 0, false, false),
    EVIL_MAGE_1(224, MONSTER, 0, false, false),
    EVIL_MAGE_2(225, MONSTER, 0, false, false),
    EVIL_MAGE_3(226, MONSTER, 0, false, false),
    EVIL_MAGE_4(227, MONSTER, 0, false, false),
    LICH_1(228, MONSTER, 0, false, false),
    LICH_2(229, MONSTER, 0, false, false),
    LICH_3(230, MONSTER, 0, false, false),
    LICH_4(231, MONSTER, 0, false, false),
    LAVA_LIZARD_1(232, MONSTER, 0, false, false),
    LAVA_LIZARD_2(233, MONSTER, 0, false, false),
    LAVA_LIZARD_3(234, MONSTER, 0, false, false),
    LAVA_LIZARD_4(235, MONSTER, 0, false, false),
    ZORN_1(236, MONSTER, 0, false, false),
    ZORN_2(237, MONSTER, 0, false, false),
    ZORN_3(238, MONSTER, 0, false, false),
    ZORN_4(239, MONSTER, 0, false, false),
    DAEMON_1(240, MONSTER, 0, false, false),
    DAEMON_2(241, MONSTER, 0, false, false),
    DAEMON_3(242, MONSTER, 0, false, false),
    DAEMON_4(243, MONSTER, 0, false, false),
    HYDRA_1(244, MONSTER, 0, false, false),
    HYDRA_2(245, MONSTER, 0, false, false),
    HYDRA_3(246, MONSTER, 0, false, false),
    HYDRA_4(247, MONSTER, 0, false, false),
    DRAGON_1(248, MONSTER, 0, false, false),
    DRAGON_2(249, MONSTER, 0, false, false),
    DRAGON_3(250, MONSTER, 0, false, false),
    DRAGON_4(251, MONSTER, 0, false, false),
    BALRON_1(252, MONSTER, 0, false, false),
    BALRON_2(253, MONSTER, 0, false, false),
    BALRON_3(254, MONSTER, 0, false, false),
    BALRON_4(255, MONSTER, 0, false, false);

    private final int index;

    private final TileType type;

    private final int walkability;

    private final boolean opaque;

    private final boolean canTalkThrough;
    
    Tile(int index, TileType type, int walkability, boolean opaque, boolean canTalkThrough) {
        this.index = index;
        this.type = type;
        this.walkability = walkability;
        this.opaque = opaque;
        this.canTalkThrough = canTalkThrough;
    }

    public static Tile forIndex(int index) {
        return Stream.of(values()).filter(tile -> tile.index() == index).findAny().orElseThrow(IllegalArgumentException::new);
    }

    public int index() {
        return index;
    }

    public TileType type() {
        return type;
    }

    public int walkability() {
        return walkability;
    }

    public boolean opaque() {
        return opaque;
    }

    public boolean canTalkAcross() {
        return canTalkThrough;
    }
}
